### ISSUE TITLE
Virtualenv Folder

### ISSUE THREAD

**Issue by ahmadsyafrudin** [firmanwibowo/upload-file-to-server#1]
Lebih bagusnya, kalo folder virtualenv nya jangan dimasukin ke project. soalnya dia pake absolute path/ symbolic link. coba perhatiin disini : https://github.com/firmanwibowo/upload-file-to-server/blob/master/virtual/lib/python3.4/heapq.py . isinya symbolic link semua

**Comment by firmanwibowo** [comment]
efek dari absolute path/symbolic link ituh apah bang. apakah jadi ga bisa di jalanin di python2 atau gimna..?

**Comment by erdepe-dad** [comment]
Efek nya, ketika orang lain clone project lo. Folder itu ga ada kegunaannya
sama sekali. Dan ketika mau di source virtualenv/bin/activate . Itu g
bakalan jalan. Soalnya perbedaan struktur folder/directory lo dan yang
clone project lo/orang lain.
